= Getting Started with Spring Cloud

In this workshop, we’ll teach you how to create a cloud native application using an API-first approach.
We’ll also use an API gateway to easily direct our traffic to one of our application instances.
We’ll also implement an application architecture that boosts resiliency in the face of unforeseen changes.
By the end of this workshop, you’ll have a starting point that you can use for your next application!

== What You Will Do

- Define a contract between two applications
- Create a basic Spring Boot application
- Deploy and run the application on Kubernetes
- Configure an API gateway
- Make your application more resilient

We don't cover all the features of Spring and Spring Cloud.
For more information you can check out the https://spring.io/guides[Spring guides^] or https://spring.io/projects[Spring project homepages^].

We also don't cover all the options available for building container images.
There is a https://spring.io/guides/topicals/spring-boot-docker/[Spring Boot topical guide^] covering some of those options in more detail.

When it comes to deploying the application to Kubernetes, there are far too many options to cover them all in one tutorial.
This workshop will use the Kubernetes CLI to deploy and configure our applications.
